variables:
    no_vars: ""

jobs:

  - job: ALL_Runtimes_On_Bionic
    variables:
      OS: Linux
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 10
    pool:
      image: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

trigger:
  - master

pr:
  branches:
    exclude:
      - '*'


