name: $(BuildID).$(Date:yyyyMMdd)
variables:
    no_vars: ""

jobs:

  - job: LinuxTaskStats_On_Focal
    variables:
      OS: Linux
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 10
    pool:
      image: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

trigger:
  - master

pr:
  branches:
    exclude:
      - '*'


